name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: |
        cd PlaywrightAutomation
        npm ci

    - name: Install Playwright Browsers
      run: |
        cd PlaywrightAutomation
        npx playwright install --with-deps

    - name: Run Playwright tests
      env:
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        MONGO: ${{ secrets.MONGO }}
        MONGODB_NAME: ${{ secrets.MONGO }}
        MONGODB_LISTINGNAME: ${{ secrets.MONGO }}
        MONGODB_LISTINGVALUE: ${{ secrets.MONGO }}
        MONGODB_USERNAME: ${{ secrets.MONGO }}
        MONGODB_EMAIL: ${{ secrets.MONGO }}
        MONGODB_PASSWORD: ${{ secrets.MONGO }}
        MONGODB_COLLECTION1: ${{ secrets.MONGO }}
        MONGODB_COLLECTION2: ${{ secrets.MONGO }}
      run: |
        cd PlaywrightAutomation
        npx playwright test

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: PlaywrightAutomation/playwright-report/
        retention-days: 30
